"""empty message

Revision ID: 178eaa44eade
Revises: 73b25d6685b7
Create Date: 2023-11-17 15:58:15.331357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178eaa44eade'
down_revision = '73b25d6685b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['carid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
