"""3rd migration

Revision ID: 380c2fa525d5
Revises: 747fb3145f66
Create Date: 2023-11-12 21:47:42.517354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380c2fa525d5'
down_revision = '747fb3145f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
