"""5th migration

Revision ID: 628db77503d9
Revises: ece5a294b842
Create Date: 2023-11-12 21:48:40.617545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628db77503d9'
down_revision = 'ece5a294b842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage',
    sa.Column('carid', sa.Integer(), nullable=False),
    sa.Column('lastusedDate', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('carid', 'id')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('carid', sa.String(), nullable=True),
    sa.Column('phno', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('userid', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('garage')
    # ### end Alembic commands ###
