"""empty message

Revision ID: 73b25d6685b7
Revises: 00f213bee8fe
Create Date: 2023-11-17 13:37:25.159259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b25d6685b7'
down_revision = '00f213bee8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('carid', sa.String(), nullable=True),
    sa.Column('phno', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('phno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
