"""2nd migration

Revision ID: 747fb3145f66
Revises: c74fea22332d
Create Date: 2023-11-12 21:46:36.251196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747fb3145f66'
down_revision = 'c74fea22332d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('garage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
